=== chenmingrang/study-space/webService/XMLTest/dtd/classRoom.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT classRoom (claDesc,claName,students)>
<!ATTLIST classRoom id ID #REQUIRED>
<!ELEMENT claDesc (#PCDATA)>
<!ELEMENT claName (#PCDATA)>
<!ELEMENT students (student+)>
<!ELEMENT student (stuId,stuName,grade)>
<!ELEMENT stuId (#PCDATA)>
<!ELEMENT stuName (#PCDATA)>
<!ELEMENT grade (#PCDATA)>

=== chenmingrang/study-space/webService/XMLTest/dtd/classRoom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classRoom SYSTEM "classRoom.dtd">
<classRoom id="cls1">
    <claDesc>java中级班</claDesc>
    <claName>三年二班</claName>
    <students>
        <student>
           <stuId>1</stuId>
           <stuName>jack</stuName>
           <grade>90</grade>
        </student>
        <student>
           <stuId>2</stuId>
           <stuName>tom</stuName>
           <grade>95</grade>
        </student>
    </students>
</classRoom>
